class Landmark {
  final String id;
  final String name;
  final String description;
  final String city;
  final String period;
  final String category;
  final double? latitude;
  final double? longitude;

  const Landmark({
    required this.id,
    required this.name,
    required this.description,
    required this.city,
    required this.period,
    required this.category,
    this.latitude,
    this.longitude,
  });
}

const List<Landmark> mockLandmarks = [
  Landmark(
    id: 'hagia_sophia',
    name: 'Ayasofya',
    description: 'Bizans İmparatoru I. Justinianus tarafından 537 yılında inşa ettirilen yapı, yaklaşık bin yıl boyunca dünyanın en büyük katedrali olma özelliğini korumuştur. 1453\'te camiye, 1934\'te müzeye, 2020\'de tekrar camiye dönüştürülmüştür.',
    city: 'İstanbul',
    period: 'MS 537',
    category: 'Dini Yapı',
    latitude: 41.0086,
    longitude: 28.9802,
  ),
  Landmark(
    id: 'topkapi',
    name: 'Topkapı Sarayı',
    description: 'Osmanlı İmparatorluğu\'nun yaklaşık 400 yıl boyunca yönetim merkezi olan saray, Fatih Sultan Mehmet tarafından 1459\'da inşa ettirilmiştir. Dört avlusu ve hazinesiyle dünyanın en büyük saray müzelerinden biridir.',
    city: 'İstanbul',
    period: 'MS 1459',
    category: 'Saray',
    latitude: 41.0115,
    longitude: 28.9833,
  ),
  Landmark(
    id: 'blue_mosque',
    name: 'Sultanahmet Camii',
    description: 'Sultan I. Ahmed tarafından 1616\'da tamamlanan cami, altı minaresiyle Osmanlı mimarisinin şaheserlerinden biridir. İç mekânı 20.000\'den fazla İznik çinisiyle süslüdür.',
    city: 'İstanbul',
    period: 'MS 1616',
    category: 'Dini Yapı',
    latitude: 41.0054,
    longitude: 28.9768,
  ),
  Landmark(
    id: 'dolmabahce',
    name: 'Dolmabahçe Sarayı',
    description: 'Sultan Abdülmecid tarafından 1856\'da yaptırılan saray, Avrupa Barok mimarisini Osmanlı sanat anlayışıyla birleştirmektedir. Atatürk\'ün vefat ettiği yer olarak da tarihi öneme sahiptir.',
    city: 'İstanbul',
    period: 'MS 1856',
    category: 'Saray',
    latitude: 41.0391,
    longitude: 29.0008,
  ),
  Landmark(
    id: 'galata_tower',
    name: 'Galata Kulesi',
    description: 'Cenevizliler tarafından 1348\'de inşa edilen kule, İstanbul\'un en belirgin simgelerinden biridir. 67 metre yüksekliğiyle şehrin panoramik manzarasını sunar.',
    city: 'İstanbul',
    period: 'MS 1348',
    category: 'Kule',
    latitude: 41.0256,
    longitude: 28.9740,
  ),
  Landmark(
    id: 'ephesus',
    name: 'Efes Antik Kenti',
    description: 'MÖ 10. yüzyılda kurulan, Roma döneminde Anadolu\'nun en büyük şehirlerinden biri olan antik kent; Celsus Kütüphanesi, Büyük Tiyatro ve Meryem Ana Evi ile ünlüdür.',
    city: 'İzmir',
    period: 'MÖ 10. yüzyıl',
    category: 'Antik Kent',
    latitude: 37.9397,
    longitude: 27.3414,
  ),
  Landmark(
    id: 'cappadocia',
    name: 'Kapadokya Peri Bacaları',
    description: 'Milyonlarca yıl önce volkanik patlamalar sonucu oluşan tüf kayaçların rüzgar ve yağmur erozyonuyla şekillenmesiyle ortaya çıkan peri bacaları, eşsiz bir doğal miras alanı oluşturmaktadır.',
    city: 'Nevşehir',
    period: 'Doğal Oluşum',
    category: 'Doğal Miras',
    latitude: 38.6431,
    longitude: 34.8289,
  ),
  Landmark(
    id: 'pamukkale',
    name: 'Pamukkale Travertenleri',
    description: 'Kalsiyum karbonat içeren termal suların yüzyıllar boyunca birikimiyle oluşan beyaz kireçtaşı teraslar, Hierapolis antik kentiyle birlikte UNESCO Dünya Mirası Listesi\'nde yer almaktadır.',
    city: 'Denizli',
    period: 'Doğal Oluşum',
    category: 'Doğal Miras',
    latitude: 37.9197,
    longitude: 29.1194,
  ),
  Landmark(
    id: 'nemrut',
    name: 'Nemrut Dağı',
    description: 'MÖ 1. yüzyılda Kommagene Kralı I. Antiokhos tarafından yaptırılan anıt mezar, devasa heykel başları ve muhteşem gün doğumu manzarasıyla UNESCO listesindedir.',
    city: 'Adıyaman',
    period: 'MÖ 1. yüzyıl',
    category: 'Antik Yapı',
    latitude: 37.9808,
    longitude: 38.7411,
  ),
  Landmark(
    id: 'troy',
    name: 'Troya Antik Kenti',
    description: 'Homeros\'un İlyada destanına konu olan efsanevi kent, MÖ 3000\'den MS 500\'e kadar kesintisiz iskân görmüştür. Tahta at replikası ve kazı alanları turistlerin ilgisini çekmektedir.',
    city: 'Çanakkale',
    period: 'MÖ 3000',
    category: 'Antik Kent',
    latitude: 39.9572,
    longitude: 26.2387,
  ),
  Landmark(
    id: 'aspendos',
    name: 'Aspendos Tiyatrosu',
    description: 'MS 2. yüzyılda Roma İmparatoru Marcus Aurelius döneminde inşa edilen tiyatro, dünyanın en iyi korunmuş Roma tiyatrolarından biridir. 15.000 kişilik kapasitesiyle günümüzde hâlâ etkinliklere ev sahipliği yapmaktadır.',
    city: 'Antalya',
    period: 'MS 2. yüzyıl',
    category: 'Antik Yapı',
    latitude: 36.9394,
    longitude: 31.1714,
  ),
  Landmark(
    id: 'perge',
    name: 'Perge Antik Kenti',
    description: 'MÖ 1000\'li yıllara dayanan antik kent, Helenistik ve Roma dönemlerine ait anıtsal kapıları, sütunlu caddeleri ve stadyumuyla öne çıkmaktadır.',
    city: 'Antalya',
    period: 'MÖ 1000',
    category: 'Antik Kent',
    latitude: 36.9614,
    longitude: 30.8547,
  ),
  Landmark(
    id: 'aphrodisias',
    name: 'Afrodisias Antik Kenti',
    description: 'Afrodit\'e adanmış bu antik kent, Roma döneminin en önemli heykel okullarından birine ev sahipliği yapmıştır. UNESCO Dünya Mirası olarak tescil edilmiş stadyum ve tetrapylon yapılarıyla ünlüdür.',
    city: 'Aydın',
    period: 'MÖ 5. yüzyıl',
    category: 'Antik Kent',
    latitude: 37.7086,
    longitude: 28.7228,
  ),
  Landmark(
    id: 'didyma',
    name: 'Didim Apollon Tapınağı',
    description: 'Antik çağın en büyük tapınaklarından biri olan yapı, MÖ 4. yüzyılda Miletliler tarafından başlatılmış ve asla tamamlanamamıştır. Dev sütunları ve kehanet geleneğiyle öne çıkmaktadır.',
    city: 'Aydın',
    period: 'MÖ 4. yüzyıl',
    category: 'Antik Yapı',
    latitude: 37.3833,
    longitude: 27.2528,
  ),
  Landmark(
    id: 'bodrum_castle',
    name: 'Bodrum Kalesi',
    description: 'Haçlı Şövalyeleri tarafından 1402\'de inşa edilen kale, Halikarnassos Mozolesi\'nin kalıntılarından elde edilen taşlarla yapılmıştır. Günümüzde Sualtı Arkeoloji Müzesi\'ne ev sahipliği yapmaktadır.',
    city: 'Muğla',
    period: 'MS 1402',
    category: 'Kale',
    latitude: 37.0342,
    longitude: 27.4241,
  ),
  Landmark(
    id: 'rumeli_hisari',
    name: 'Rumeli Hisarı',
    description: 'Fatih Sultan Mehmet tarafından İstanbul\'un fethinden önce 1452\'de yaptırılan kale, Boğaz\'ın en dar noktasında inşa edilmiştir. 3 büyük kule ve 13 küçük kulesiyle dikkat çekmektedir.',
    city: 'İstanbul',
    period: 'MS 1452',
    category: 'Kale',
    latitude: 41.0853,
    longitude: 29.0561,
  ),
  Landmark(
    id: 'selimiye',
    name: 'Edirne Selimiye Camii',
    description: 'Mimar Sinan\'ın ustalık eseri olarak nitelendirdiği cami, Sultan II. Selim adına 1574\'te tamamlanmıştır. Dört minaresi ve 31,5 metrelik muazzam kubbesiyle Osmanlı mimarisinin zirvesini temsil eder.',
    city: 'Edirne',
    period: 'MS 1574',
    category: 'Dini Yapı',
    latitude: 41.6781,
    longitude: 26.5597,
  ),
  Landmark(
    id: 'bursa_ulucami',
    name: 'Bursa Ulucami',
    description: 'Sultan Yıldırım Bayezid tarafından 1399\'da yaptırılan cami, 20 kubbesi ve iki minaresiyle Osmanlı mimarisinin erken dönem şaheserlerinden biridir. İçindeki şadırvanı ve hat eserleriyle öne çıkmaktadır.',
    city: 'Bursa',
    period: 'MS 1399',
    category: 'Dini Yapı',
    latitude: 40.1839,
    longitude: 29.0608,
  ),
  Landmark(
    id: 'ani_ruins',
    name: 'Ani Harabeleri',
    description: 'Orta çağda Ermeni Bagratuni Krallığı\'nın başkenti olan kent, MS 961\'de kurulmuştur. "Bin ve bir kiliseler şehri" olarak da anılan Ani, UNESCO Dünya Mirası statüsündedir.',
    city: 'Kars',
    period: 'MS 961',
    category: 'Antik Kent',
    latitude: 40.5058,
    longitude: 43.5725,
  ),
  Landmark(
    id: 'ishak_pasha',
    name: 'İshak Paşa Sarayı',
    description: '17. ve 18. yüzyıllarda inşa edilen saray, Osmanlı, Selçuklu, İran ve Ermeni mimarisi unsurlarını bünyesinde barındırmaktadır. Doğu Anadolu\'nun Ağrı Dağı manzarasına hâkim konumda yer almaktadır.',
    city: 'Ağrı',
    period: 'MS 17. yüzyıl',
    category: 'Saray',
    latitude: 39.7247,
    longitude: 44.0931,
  ),
  Landmark(
    id: 'sumela',
    name: 'Sümela Manastırı',
    description: 'MS 4. yüzyılda kayalıklara oyularak inşa edilen Rum Ortodoks manastırı, Trabzon\'un Altındere Vadisi\'nde 1200 metre yükseklikte bulunmaktadır.',
    city: 'Trabzon',
    period: 'MS 4. yüzyıl',
    category: 'Dini Yapı',
    latitude: 40.6919,
    longitude: 39.6631,
  ),
  Landmark(
    id: 'gobekli_tepe',
    name: 'Göbekli Tepe',
    description: 'MÖ 10.000\'e tarihlenen yapı kompleksi, bilinen en eski tapınak olma özelliğini taşımaktadır. T-şeklindeki devasa sütunları, insanlık tarihinin yeniden yorumlanmasına yol açmıştır.',
    city: 'Şanlıurfa',
    period: 'MÖ 10.000',
    category: 'Arkeolojik Alan',
    latitude: 37.2231,
    longitude: 38.9225,
  ),
  Landmark(
    id: 'harran',
    name: 'Harran Antik Kenti',
    description: 'Dünyada kesintisiz iskânı olan en eski yerleşim yerlerinden biri olan Harran, konik kubbeli evleri ve ünlü üniversitesiyle tarihe geçmiştir. Hz. İbrahim\'in bir süre ikamet ettiği rivayet edilmektedir.',
    city: 'Şanlıurfa',
    period: 'MÖ 3000',
    category: 'Antik Kent',
    latitude: 36.8631,
    longitude: 39.0275,
  ),
  Landmark(
    id: 'mount_ararat',
    name: 'Ağrı Dağı',
    description: '5137 metre yüksekliğiyle Türkiye\'nin en yüksek noktası olan Ağrı Dağı, Nuh\'un Gemisi efsanesiyle bütünleşmiş kutsal bir dağdır. Yılın büyük bölümünde karla kaplı zirvesiyle görkemli bir manzara sunar.',
    city: 'Ağrı',
    period: 'Doğal Oluşum',
    category: 'Doğal Miras',
    latitude: 39.7022,
    longitude: 44.2983,
  ),
  Landmark(
    id: 'konya_mevlana',
    name: 'Mevlana Müzesi',
    description: 'Mevlana Celaleddin Rumi\'nin türbesini barındıran yapı, 13. yüzyılda inşa edilmiş olup yeşil kubbesiyle Konya\'nın simgesi haline gelmiştir. Her yıl milyonlarca ziyaretçi çekmektedir.',
    city: 'Konya',
    period: 'MS 13. yüzyıl',
    category: 'Dini Yapı',
    latitude: 37.8714,
    longitude: 32.5047,
  ),
  Landmark(
    id: 'alanya_castle',
    name: 'Alanya Kalesi',
    description: 'Selçuklu Sultanı I. Alaeddin Keykubad tarafından 1226\'da yaptırılan kale, Akdeniz kıyısında yükselen kaya üzerinde konumlanmaktadır. Kızıl Kule ve tersanesiyle birlikte önemli bir yapı topluluğu oluşturmaktadır.',
    city: 'Antalya',
    period: 'MS 1226',
    category: 'Kale',
    latitude: 36.5442,
    longitude: 32.0156,
  ),
  Landmark(
    id: 'aizanoi',
    name: 'Aizanoi Antik Kenti',
    description: 'Zeus Tapınağı\'nın bulunduğu antik kent, Roma dönemine ait en iyi korunmuş tapınak komplekslerinden birini barındırmaktadır. Son yıllarda yapılan kazılarda tarihin ilk borsası olduğu değerlendirilen yapı gün yüzüne çıkarılmıştır.',
    city: 'Kütahya',
    period: 'MS 2. yüzyıl',
    category: 'Antik Kent',
    latitude: 39.0631,
    longitude: 29.6447,
  ),
  Landmark(
    id: 'hattusha',
    name: 'Hattuşa',
    description: 'Hitit İmparatorluğu\'nun başkenti olan Hattuşa, MÖ 17. yüzyılda kurulmuştur. Aslan ve sfenks kapıları ile Yazılıkaya kaya tapınağıyla UNESCO Dünya Mirası statüsündedir.',
    city: 'Çorum',
    period: 'MÖ 17. yüzyıl',
    category: 'Antik Kent',
    latitude: 40.0194,
    longitude: 34.6156,
  ),
  Landmark(
    id: 'sardis',
    name: 'Sardes Antik Kenti',
    description: 'Lidya Krallığı\'nın başkenti olan Sardes, tarihteki ilk altın ve gümüş sikkelerin basıldığı yer olarak bilinmektedir. Artemis Tapınağı ve Roma dönemi hamamları önemli yapılar arasındadır.',
    city: 'Manisa',
    period: 'MÖ 7. yüzyıl',
    category: 'Antik Kent',
    latitude: 38.4881,
    longitude: 28.0547,
  ),
  Landmark(
    id: 'pergamon',
    name: 'Bergama Akropolü',
    description: 'Hellenistik dönemin önde gelen kültür merkezlerinden biri olan Pergamon, Mısır\'dan sonra dünyanın en büyük kütüphanesine ev sahipliği yapmıştır. Asklepion sağlık merkezi ve Zeus Sunağı ile ünlüdür.',
    city: 'İzmir',
    period: 'MÖ 3. yüzyıl',
    category: 'Antik Kent',
    latitude: 39.1328,
    longitude: 27.1844,
  ),
  Landmark(
    id: 'letoon',
    name: 'Letoon Kutsal Alanı',
    description: 'Lykia uygarlığına ait bu kutsal alan, Leto, Artemis ve Apollon\'a adanmış üç tapınaktan oluşmaktadır. Xanthos ile birlikte UNESCO Dünya Mirası listesine alınmıştır.',
    city: 'Muğla',
    period: 'MÖ 5. yüzyıl',
    category: 'Antik Yapı',
    latitude: 36.3478,
    longitude: 29.2869,
  ),
  Landmark(
    id: 'xanthos',
    name: 'Ksanthos Antik Kenti',
    description: 'Lykia Birliği\'nin başkenti olan Ksanthos, tarihin en eski demokrasi örneklerinden birine tanıklık etmiştir. Harpy Anıtı ve mezar stelleri önemli eserler arasındadır.',
    city: 'Muğla',
    period: 'MÖ 7. yüzyıl',
    category: 'Antik Kent',
    latitude: 36.3567,
    longitude: 29.3197,
  ),
  Landmark(
    id: 'hierapolis',
    name: 'Hierapolis Antik Kenti',
    description: 'Pamukkale travertenlerinin hemen üzerinde konumlanan antik kent, Roma döneminin önemli bir kaplıca şehridir. Büyük nekropolü ve tiyatrosuyla öne çıkan kent, Pamukkale ile birlikte UNESCO listesindedir.',
    city: 'Denizli',
    period: 'MÖ 2. yüzyıl',
    category: 'Antik Kent',
    latitude: 37.9253,
    longitude: 29.1269,
  ),
  Landmark(
    id: 'catalhoyuk',
    name: 'Çatalhöyük',
    description: 'MÖ 7500\'e tarihlenen Neolitik dönem yerleşim yeri, dünyanın en eski şehirlerinden biri kabul edilmektedir. Bitişik evleri ve duvar resimleriyle insanlığın en önemli arkeolojik keşiflerinden birini oluşturmaktadır.',
    city: 'Konya',
    period: 'MÖ 7500',
    category: 'Arkeolojik Alan',
    latitude: 37.6672,
    longitude: 32.8267,
  ),
  Landmark(
    id: 'amasya_tombs',
    name: 'Amasya Kral Kaya Mezarları',
    description: 'MÖ 4.-1. yüzyıllara ait Pontus krallığının kaya mezarları, Yeşilırmak vadisine hâkim kayalıklara oyulmuştur. Gece aydınlatmaları ile eşsiz bir manzara sunan mezarlar, şehrin simgesi haline gelmiştir.',
    city: 'Amasya',
    period: 'MÖ 4. yüzyıl',
    category: 'Antik Yapı',
    latitude: 40.6533,
    longitude: 35.8339,
  ),
  Landmark(
    id: 'divriği',
    name: 'Divriği Ulu Camii ve Darüşşifası',
    description: '1228 yılında Mengücek Beyliği döneminde inşa edilen yapı, olağanüstü taş işçiliğiyle UNESCO Dünya Mirası statüsündedir. Portalleri üzerindeki bitkisel ve geometrik süslemeler eşsiz bir özgünlük taşımaktadır.',
    city: 'Sivas',
    period: 'MS 1228',
    category: 'Dini Yapı',
    latitude: 39.3714,
    longitude: 38.1142,
  ),
  Landmark(
    id: 'dara',
    name: 'Dara Antik Kenti',
    description: 'MS 5. yüzyılda Bizanslılar tarafından kurulan sınır kenti, devasa sarnıcı ve nekropolüyle öne çıkmaktadır. Mezopotamya ovasının ortasında yükselen surları dikkat çekicidir.',
    city: 'Mardin',
    period: 'MS 5. yüzyıl',
    category: 'Antik Kent',
    latitude: 37.1864,
    longitude: 40.9556,
  ),
  Landmark(
    id: 'mardin_old_city',
    name: 'Mardin Eski Şehri',
    description: 'Mezopotamya ovasına hâkim kayalık üzerine kurulu tarihi Mardin, sarı taştan yapılmış evleri ve Deyrulzafaran Manastırı ile UNESCO Geçici Listesi\'ndedir. Çok kültürlü dokusuyla eşsiz bir mimari miras barındırmaktadır.',
    city: 'Mardin',
    period: 'MS 4. yüzyıl',
    category: 'Tarihi Kent',
    latitude: 37.3128,
    longitude: 40.7394,
  ),
  Landmark(
    id: 'safranbolu',
    name: 'Safranbolu Tarihi Kent Merkezi',
    description: 'Osmanlı dönemi sivil mimarisinin en iyi korunmuş örneklerini barındıran Safranbolu, 1994\'ten bu yana UNESCO Dünya Mirası Listesi\'ndedir. Ahşap çatkılı konakları ve çarşısıyla tarihe ışık tutmaktadır.',
    city: 'Karabük',
    period: 'MS 17. yüzyıl',
    category: 'Tarihi Kent',
    latitude: 41.2489,
    longitude: 32.6942,
  ),
  Landmark(
    id: 'alacahoyuk',
    name: 'Alacahöyük',
    description: 'MÖ 4000\'e uzanan tarihiyle Anadolu\'nun önemli arkeolojik alanlarından biridir. Hitit dönemine ait sfenksli kapısı ve güneş diskleriyle ünlüdür.',
    city: 'Çorum',
    period: 'MÖ 4000',
    category: 'Arkeolojik Alan',
    latitude: 40.2356,
    longitude: 34.6875,
  ),
  Landmark(
    id: 'kizkalesi',
    name: 'Kız Kalesi',
    description: 'Mersin açıklarında küçük bir adacık üzerinde yükselen deniz kalesi, 12. yüzyılda Ermeni Kilikya Krallığı döneminde inşa edilmiştir. Efsanevi hikâyesi ve deniz üzerindeki konumuyla ikonik bir görsel sunar.',
    city: 'Mersin',
    period: 'MS 12. yüzyıl',
    category: 'Kale',
    latitude: 36.4611,
    longitude: 34.1508,
  ),
  Landmark(
    id: 'termessos',
    name: 'Termessos Antik Kenti',
    description: 'Toros Dağları\'nın sarp yamaçlarına kurulu antik kent, Büyük İskender tarafından bile alınamayan surlarıyla ünlüdür. Orman içinde saklı tiyatrosu ve nekropolü ziyaretçilere unutulmaz bir deneyim sunmaktadır.',
    city: 'Antalya',
    period: 'MÖ 5. yüzyıl',
    category: 'Antik Kent',
    latitude: 37.0708,
    longitude: 30.4628,
  ),
  Landmark(
    id: 'hasankeyf',
    name: 'Hasankeyf Antik Kenti',
    description: 'Tigris Nehri kıyısında 12.000 yıllık tarihe sahip Hasankeyf, kaya oyma evleri, El Rızk Camii ve Zeynel Bey Türbesi ile önemli bir kültürel miras alanıdır.',
    city: 'Batman',
    period: 'MÖ 10.000',
    category: 'Antik Kent',
    latitude: 37.7167,
    longitude: 41.4056,
  ),
  Landmark(
    id: 'tarsus',
    name: 'Tarsus Tarihi Merkezi',
    description: 'Hz. Pavlus\'un doğduğu, Kleopatra ile Julius Caesar\'ın buluştuğu rivayet edilen antik kent, Gözlükule höyüğü ve Kleopatra Kapısı ile önemli bir tarihi merkezdir.',
    city: 'Mersin',
    period: 'MÖ 2000',
    category: 'Tarihi Kent',
    latitude: 36.9167,
    longitude: 34.8956,
  ),
  Landmark(
    id: 'bayrakli_mound',
    name: 'Kadifekale',
    description: 'MÖ 4. yüzyılda Büyük İskender\'in emriyle kurulan İzmir\'in akropolü, kentin panoramik manzarasını sunmaktadır. Tarihi surları ve Osmanlı dönemi kulesinin kalıntılarıyla dikkat çekmektedir.',
    city: 'İzmir',
    period: 'MÖ 4. yüzyıl',
    category: 'Kale',
    latitude: 38.4178,
    longitude: 27.1436,
  ),
  Landmark(
    id: 'prusias_ad_hypium',
    name: 'Prusias ad Hypium',
    description: 'Bithynia Krallığı\'na ait antik kent, Roma döneminin etkileyici tiyatrosu ve su kemerleriyle öne çıkmaktadır. Kentin ismini aldığı Prusias\'ın sarayına atfedilen kalıntılar da görülebilmektedir.',
    city: 'Düzce',
    period: 'MÖ 3. yüzyıl',
    category: 'Antik Kent',
    latitude: 40.9194,
    longitude: 31.1514,
  ),
  Landmark(
    id: 'nicaea',
    name: 'İznik Tarihi Surları',
    description: 'MS 325\'te Birinci Konsil\'e ev sahipliği yapan Nicaea antik kenti, dönemine ait surları, Ayasofya kilisesi kalıntıları ve Osmanlı döneminden İznik çini sanatıyla önem taşımaktadır.',
    city: 'Bursa',
    period: 'MÖ 4. yüzyıl',
    category: 'Tarihi Kent',
    latitude: 40.4300,
    longitude: 29.7211,
  ),
  Landmark(
    id: 'ottoman_hans',
    name: 'Bursa Kapalıçarşısı ve Hanlar Bölgesi',
    description: 'Osmanlı ticaret yapısının en canlı örneklerinden biri olan Kapalıçarşı ve çevresindeki tarihi hanlar, 14.-15. yüzyıllarda inşa edilmiştir. Koza Hanı başta olmak üzere pek çok han günümüzde de ticari işlevini sürdürmektedir.',
    city: 'Bursa',
    period: 'MS 14. yüzyıl',
    category: 'Tarihi Yapı',
    latitude: 40.1828,
    longitude: 29.0614,
  ),
  Landmark(
    id: 'beyşehir_lake',
    name: 'Eşrefoğlu Camii',
    description: 'Ahşap sütunlu camilerin en büyük ve en iyi korunmuş örneği olan Eşrefoğlu Camii, 1297\'de inşa edilmiştir. 48 ahşap direği ve özgün minaresiyle Anadolu Selçuklu mimarisinin şaheserlerinden kabul edilmektedir.',
    city: 'Konya',
    period: 'MS 1297',
    category: 'Dini Yapı',
    latitude: 37.6811,
    longitude: 31.7261,
  ),
];
